### ISSUE TITLE
Ignore additional --gtp flag

### ISSUE THREAD

**Issue by Atarust** [SabakiHQ/LeelaSabaki#7] opened 2018-02-09 17:06 UTC
Error message is shown when trying to play with leelaSabaki:

`"Current board arrangement can’t be recreated on the GTP engine."`

Engine is called with: 
path: my_path/leelasabaki-linux
arguments: my_path/leelaz --gtp -w my_path/weights.txt --playouts 10 --noponder

Playing with leelaz without leelasabaki-linux works fine. Using sabaki-v0.33.2-linux-x64.AppImage with leelsabaki-v0.3.0-linux-macos-win-x64.7z under ubuntu.

What am I doing wrong?

**Comment by yishn** [comment] 2018-02-09 19:05
That's an interesting bug... but I can't reproduce this on my Windows machine. If Sabaki works with leelaz, but not with LeelaSabaki, there's definitely something wrong. Did you load some SGF file and start playing in the middle of the game? If so, can you provide it? Also, see if omitting the `--gtp` flag does something.

**Comment by Atarust** [comment] 2018-02-09 20:36
wow. that's it. 

Without the --gtp the both work. 
Thank you. 

Could you add those example path and argument lines to the howto?

**Comment by yishn** [comment] 2018-02-09 20:50
Good idea!

**Comment by BorisNA** [comment] 2018-02-15 11:18
It looks like I've got the same issue. 
Windows, Sabaki 0.33.3. LeelaZ and Leela 0.11.

For example, for LeelaZ. GTP works Ok according to the console, but the error "Current board arrangement..." still appears.

```
path: c:\_MyPrograms\LeelaZ\leelaz.exe 
Arguments: -w weights.txt --playouts 100 --noponder
```

Leela without weights file (if the path should be absolute) - the same result.

**Comment by yishn** [comment] 2018-02-15 16:32
> I've got it. Plain vanilla leela requires "--gtp" and the "leelasabaki" - doesn't. I believe that is the source of confusion. May be it will be a better solution to add a code to strip or ignore "--gtp" part for the leelasabaki?

You're exactly right. That's a good idea! I'll keep this open for the suggestion.

**Comment by WarChimp** [comment] 2018-03-23 22:36
I am also getting the same error
> "Current board arrangement can’t be recreated on the GTP engine."

I am on a windows 7 machine using Sabaki 0.33.3
I can't seem to work out what the issue is. Here is a screenshot of my command line.

![image](https://user-images.githubusercontent.com/3951876/37855983-15f8c2ac-2f46-11e8-9ada-756198d27c7b.png)

Here is the error I am getting when I boot a game with LeelaZero
![image](https://user-images.githubusercontent.com/3951876/37856117-b8909a9e-2f46-11e8-8874-927877d9712a.png)

Am I missing something obvious?

**Comment by yishn** [comment] 2018-03-23 23:35
@WarChimp It seems like you're not passing the path to Leela as argument, but the path to LeelaSabaki.

**Comment by yishn** [comment] 2018-04-14 10:25
This has been fixed in master.

**Closed by yishn** 2018-04-14 10:25 UTC
Labels: enhancement
